services:
  crypto:
    build: .
    volumes:
      # bind-mount your USB-hosted repo into /workspace
      - "/media/leon/Leon's File/Nextcloud/ETSIIT/ETSHIT/Github/ECC-Thesis:/workspace:delegated"
      - bin:/workspace/bin
      - results:/workspace/results
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: bash

volumes:
  bin:
  results:
