name: Docker Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo-code
      uses: actions/checkout@v4

    - name: Pull Docker image
      run: docker pull leonfullxr/ecc-benchmarks:latest

    - name: Run Docker container
      run: |
          docker run --rm \
            -v "${{ github.workspace }}":/workspace \
            -w /workspace \
            leonfullxr/ecc-benchmarks:latest \
            make